### ISSUE TITLE
Support for ZGC / Shenandoah GC and large HEAP configurations

### ISSUE THREAD

**Issue by mfussenegger** [crate/crate#10505]
Currently we default to G1GC and recommend a HEAP configuration that stays below the Compressed Oops threshold which is around ~31.5 GB. (See [Memory configuration](https://crate.io/docs/crate/howtos/en/latest/performance/memory.html)).

Some of our users have workloads where they run GROUP BY queries on high cardinality columns. These queries can require a large amount of HEAP. That can lead to GC pressure or the queries fail with the circuit breaker.

There are several potential solutions for that:

- Optimize them to require less memory in the first place
- Support using off-heap for grouping operations
- Spill to disk when running out of heap for grouping operations
- Support configurations with large heaps

This issue here is about the last item: Improving support for configurations with large heap.

Some steps that may be necessary:

- [ ] Bump the bundled JDK to 15 once it has reached GA (2020-09-15). Both [ZGC](https://openjdk.java.net/jeps/377) and [Shenandoah](https://openjdk.java.net/jeps/379) are marked as production then.
- [ ] Configure our tests to use ZGC and Shenandoah (maybe randomize the configuration?)
- [ ] Run a performance tests on a system with a large amount of memory (128 GB or 256 GB range?). Preferable with high cardinality GROUP BY queries that we know to be problematic.
- [ ] Create or extend a how-to that describes the different GC options and elaborates on the impact

This is somewhat related to the [performance focus in Q3](https://github.com/crate/crate/issues/10256)

**Comment by amotl** [comment]
Hi. I don't know too much about it, but @WalBeh just asked me about this topic, because he is currently preparing a Prometheus metrics seminar, for which he was investigating which JVM is being bundled, and which GC is configured as default.

**Comment by zyclonite** [comment]
hi, maybe something to consider now as the generational feature was released with jdk21
i am trying it with a patched run script in production to get some data, so far so good (except the gc logs, which might need refactoring first)

**Comment by seut** [comment]
Outcome of some internal discussion:
 - We want to add some documentation about how to switch to ZGC (or Shenandoah) with warnings, stating that this is on users own risk. (but also state that we appreciate feedback on this)
 - We ask some related customer(s) to try it out and give us feedback to know how this behaves in real production scenarios.
 - If we get only positive feedback, we'd plan to include it in our test runs and officially support.
