### ISSUE TITLE
Meta: address all current `content: correction` issues

### ISSUE THREAD

**Issue by mechanomi** [crate/crate#10773]
this meta issue address all current `content: correction` issues

planned commits (on https://github.com/crate/crate/pull/10861):

- [x] Correction: Clarify `single-node` admonition and copy to shared-nothing concepts document (fixes #10058)
- [x] Correction: Add note about `doc` only being available after the first table is created (fixes https://github.com/crate/tech-writing-domain/issues/206)
- [x] Correction: Add clarification and cross-reference for object literals syntax (fixes https://github.com/crate/tech-writing-domain/issues/201)
- [x] Correction: Add missing link to the Enterprise Features document (fixes https://github.com/crate/crate/issues/10253)
- [x] ~~Correction: Update "stock host Java VM JIT compilers" link (fixes https://github.com/crate/tech-writing-domain/issues/323)~~
  - fixed in https://github.com/crate/crate/commit/f71ed405d961501326ef48d88b705f55a9c8b964
- [x] Correction: Cross-reference `blocks.read_only_allow_delete` (fixes https://github.com/crate/crate/issues/10394)
- [x] ~~Correction: Fix link to `text` data type (fixes https://github.com/crate/crate/issues/10445)~~
  - fixed by https://github.com/crate/crate/pull/10729
- [x] Correction: Fix default authentication config documentation intro (fixes #10119)
- [x] Correction: Clarify object array access syntax (fixes https://github.com/crate/crate/issues/10110)
  - spun out to a separate issue: https://github.com/crate/crate/pull/10866
- [x] Correction: Fix geospatial doc tests to catch reported errors and update corresponding example SQL (fixes https://github.com/crate/tech-writing-domain/issues/208)
- [x] Correction: Minor copyedit and some link fixes for release notes (fixes https://github.com/crate/tech-writing-domain/issues/155)
- [x] Correction: Correction: Add a note about the availability of the `KILL` statement  (fixes https://github.com/crate/crate/issues/10209)
- [x] Correction: Use HTTPS instead of HTTP for links (fixes https://github.com/crate/tech-writing-domain/issues/316)
  - fixed in https://github.com/crate/crate/pull/10861/commits/a3d7b19b3123d24c10388b44f80fd5af5918d0b1 for crate/crate
  - fixed in https://github.com/crate/crate-howtos/pull/263
  - fixed in https://github.com/crate/crate-tutorials/pull/36
  - fixed in https://github.com/crate/crash/pull/348

**Comment by mechanomi** [comment]
this is done
