### ISSUE TITLE
Backport roadmap 4.5 release 

### ISSUE THREAD

**Issue by mkleen** [crate/crate#11096]
This is the current state of applied backports which will be included into the upcoming 4.5 release. These backports have been applied in sequential order as they were committed to elasticsearch.  

### Internal Engine: 
- [x]  https://github.com/crate/crate/commit/128a831b1cd7fd4f4eace75271edba1685632930 bp: Remove pre 6.0.0 support from InternalEngine.

### Recovery/Translog/Replication:
- [x] 93a4a267b56 bp: Use peer recovery retention leases for indices without soft-deletes 
- [x] 98f1921bdbf bp: Migrate peer recovery from translog to retention lease 
- [x] 5745e699bc3 bp: Make setting index.translog.sync_interval be dynamic
- [x] 6b9b31a296d bp: Replicate write actions before fsyncing them
- [x] Extend shard level replication tests e.g. IndexShardRetentionLeaseTests, RetentionLeasesReplicationTests etc. (in progress)
- [x] Deprecate table creation without soft deletes 
- [x] Deprecate translog retention settings 

### Transport:
- [x] 51d6d361dce bp: Remove Unused Features Field on StreamOutput
- [x] 46170664f35 bp: Optimize some StreamOutput Operations
- [x] eb95549bcc5 bp: Add int indicating size of transport header
- [x] d741fdcf90e bp: Remove nodeId from BaseNodeRequest

It would be nice to get a few more simplifications in, e.g. remove the `BaseNodeRequest`, but it is not mandatory.

### Metadata:
- [x] 02f1bf7b05b bp: Make elasticsearch-node tools custom metadata-aware
- [x] 9ac478470a4 bp: Omit loading IndexMetaData when inspecting shards

### Cluster:
- [x] 2e6caa9c786 bp: Remove some leftover refs to minimum_master_nodes
- [x] 6aac9fa40f6 bp: Cluster state from API should always have a master
- [x] 485bcf78b45 bp: Omit non-masters in ClusterFormationFailureHelper

The main objective was here to remove the last remaining bits of the minimum master_node setting and archieve more stability for the tests.

### Testing:
- [x] e6eeb0a158e bp: Strengthen validateClusterFormed check
- [x] 5c9b5e53fa1 bp: ESIntegTestCase always cleans up static fields
- [x] 0b6d4b8c0b5 bp: Use dynamic port ranges for ExternalTestCluster
- [x] e745870ad5b bp: Wait for events in waitForRelocation
- [x] 0596e89f824 bp: Remove RemoteClusterConnection.ConnectedNodes
- [x] 3289b29cdfa bp: Fix port range allocation with large worker IDs
- [x] e636850999c bp: Simplify port usage in transport tests
- [x] 6dd8bfb0786 bp: Some Cleanup in Test Framework
- [x] d34f8b2d31b bp: Use unique ports per test worker
- [x] 4de26e71e63 bp: Enable node roles to be pluggable
- [x] 206dc6ebb4e bp: Allow cluster access during node restart
- [x] 28a9ba6c09e bp: Increase waiting time when check retention locks
- [x] 9e80e3223a3 bp: Remove transport client from tests
- [x] aab7f2138b8 bp: Remove `Tracer` from `MockTransportService`

The testing framework is at a stable state right now. 

### Others: 
- [x] 634d34d5bb0 bp: New setting to prevent automatically importing dangling indices
- [x] b88a9270395 bp: Enable dependent settings values to be validated
- [x] 62ff8205f84 bp: Silence lint warnings in server project - part 2
- [x] fc4b503bf73 bp: Make Snapshot Metadata Javadocs Clearer

**Comment by mkleen** [comment]
@seut @mfussenegger So far i grouped all applied backports for 4.5 into sections. My next step would be to define for each section a goal for the 4.5 release. Does this make sense to you ?
