### ISSUE TITLE
Backport missing repository/snapshot related tests

### ISSUE THREAD

**Issue by mkleen** [crate/crate#11461]
The folllowing tests should be backported if possible before the 4.6 release:

- [x] server/src/test/java/org/elasticsearch/repositories/blobstore/BlobStoreRepositoryRestoreTests.java
- [x] server/src/test/java/org/elasticsearch/repositories/blobstore/BlobStoreRepositoryTests.java
- [ ] ~~server/src/test/java/org/elasticsearch/snapshots/DedicatedClusterSnapshotRestoreIT.java~~
- [x] server/src/test/java/org/elasticsearch/snapshots/RepositoriesMetaDataSerializationTests.java
- [x] org.elasticsearch.snapshots.BlobStoreFormatIT 
- [x] org.elasticsearch.snapshots.CorruptedBlobStoreRepositoryIT
- [ ] ~~org.elasticsearch.snapshots.RepositoriesIT~~
- [x] org.elasticsearch.snapshots.MinThreadsSnapshotRestoreIT
- [x]  org.elasticsearch.snapshots.SnapshotShardsServiceIT
- [x] org.elasticsearch.repositories.blobstore.BlobStoreRepositoryRestoreTests
- [ ] ~~org.elasticsearch.snapshots.SnapshotResiliencyTests~~
