### ISSUE TITLE
First class table & partitions within cluster state

### ISSUE THREAD

**Issue by mfussenegger** [crate/crate#11939]
## Current state

CrateDB tables and partitioned tables were initially built on top of ES index and aliases functionality.

A table has a 1:1 mapping to an ES index.
A partitioned table maps to multiple ES indices and there is an alias mapping from table name to indices.

Internally we use a combination of `IndexMetadata` and `IndexTemplateMetadata` to store the information in the cluster state and have a "view" on top in the form of `DocTableInfo`.

`DocTableInfo` instances are held in-memory and only updated if needed:

https://github.com/crate/crate/blob/01dc17264b8444e7b6bf7fd4f9fa812e2c108604/server/src/main/java/io/crate/metadata/doc/DocSchemaInfo.java#L221-L287

This design saved us time & work initially, but since we integrated the ES code and maintain it ourselves and with more and more CrateDB specific functionality and requirements, the early benefits disappear and the downsides remain more visible.

- Mapping information is duplicated in templates and indices.
- The caching layer adds indirection between the source of truth and what most logic depends on, which can be a source of bugs.
- We require extra logic:
  - CREATE TABLE SQL statements are converted into index mapping/settings
  - mapping/settings are converted into DocTableInfo
  - `DocTableInfo` is converted to SQL statement (show create table)
  - There are separate listeners/hooks in both worlds:
    - IndexLifecycle related
    - DDLClusterStateModifier
  - Alter table/dynamic mapping updates both also work with different entities. The dynamic mapping update also forces us into a `source` first world - which needs to be changed in the course of https://github.com/crate/crate/issues/10025
- There is a bit of a miss-match between how we model table options and how they map to ES settings/mappings. One table option might be a mapping property, and another can be a setting.

```
   SQL statement ──────► AnalyzedStatement ──────► Mapping/settings
         ▲                                              │
         │                                              │
         │                                              ▼
         │                                          DocTableInfo
         │                                              │
         └──────────────────────────────────────────────┘
```

### Option 1

We could consider storing the SQL statement 1:1 into the cluster state. We already have parser & analyzer for it and we need that in any case. We could derive everything else from this analyzed state.

```
  SQL statement ◄───► AnalyzedStatement
         ▲                  ▲  DocTableInfo
         │                  │
         └────────┬─────────┘
                  ▼
               ClusterState
```

For ALTER TABLE we could analyze the statement, generate a diff that can be applied on the AnalyzedCreateTableStatement/DocTableInfo to generate a updated CreateTableStatement/DocTableInfo, and generate the new CREATE TABLE SQL statement from that to store in the cluster state.

### Option 2

Store DocTableInfo/Reference etc. in binary form

ClusterState would no longer have a JSON-like representation, but instead we'd use `Writable` implementations for serialization & deserialization.

### Option 3

Focus on ClusterState representation first.

New structure could look something like this:

```
tables: [
  {
    schema
    name
    mapping/schema

    index_uuid: null|string (only if not partitioned)
    partitions: [
      {
        index_uuid
        ident

        // _no_ mapping or schema
      }
    ]
  }
]
```

---

Open questions:

- [ ] Downgrade implications for hotfixes: Likely can't change storage format
- [ ] How to model the stuff? E.g. tables/partitioned tables vs. indices/templates

---

Discussion 2022-09-13

- Overall impression: Reducing the complexity would be great, but have to consider all consequences
- [x] Would probably make sense to complete the backports first

### Design considerations

- Persisted OID for relations? See https://github.com/crate/crate/issues/12106#issuecomment-1173769852
- Analyzer no longer inline, but as dedicated entities (https://github.com/crate/crate/pull/15819)

### Affected components

- CREATE TABLE
- ALTER TABLE
    - SET / RESET settings
    - drop constraints
    - add column
    - drop column
    - rename
    - open/close (?)
- Snapshots & recovery
- ...

**Comment by mfussenegger** [comment]
Continue tracking the remaining steps in https://github.com/crate/crate/issues/17518
