### ISSUE TITLE
[Meta] DBeaver / Datagrip - PG connector compatibility tracker 

### ISSUE THREAD

**Issue by proddata** [crate/crate#12101]
This is a meta ticket tracking current state of missing tables, function features for CrateDB to work with the **standard** PostgreSQL connectors in DBeaver and Datagrip. Both those tools can be used with either a CrateDB connector or using the CrateDB JDBC driver.

--- 

This list is a WIP and might not be complete

**Missing general functionality**

- [ ] `current_database()` should return `'doc'` or database need to be switched to `'crate'`
- [ ] Support for `SHOW DateStyle;`
- [ ] Support for `UNION DISTINCT` -  #12100 
- [ ] add `xmin` (and other `System Columns`) to pg_catalog tables - [see PG docs](https://www.postgresql.org/docs/14/ddl-system-columns.html)
- [ ] `oid` datatype
- [ ] `WITH` queries - #11757
- [ ] `cross join unnest(xxx) with ordinality u(u, k)`

**Missing functions**

- [ ] [pg_catalog.txid_current()](https://www.postgresql.org/docs/14/functions-info.html)
- [ ] [pg_catalog.pg_is_in_recovery()](https://www.postgresql.org/docs/14/functions-admin.html#FUNCTIONS-RECOVERY-CONTROL)
- [ ] [pg_catalog.pg_get_viewdef(t.oid, true)](https://www.postgresql.org/docs/14/functions-info.html)
- [ ] [pg_catalog.pg_relation_size(i.indexrelid)](https://www.postgresql.org/docs/14/functions-admin.html)
- [ ] [pg_tablespace_location(t.oid)](https://www.postgresql.org/docs/14/functions-info.html)

**Missing `pg_catalog` tables**

- [ ] [pg_catalog.pg_aggregate](https://www.postgresql.org/docs/14/catalog-pg-aggregate.html)
- [ ] [pg_catalog.pg_amop](https://www.postgresql.org/docs/14/catalog-pg-amop.html)
- [ ] [pg_catalog.pg_amproc](https://www.postgresql.org/docs/14/catalog-pg-amproc.html)
- [ ] [pg_catalog.pg_available_extensions](https://www.postgresql.org/docs/14/view-pg-available-extensions.html)
- [ ] [pg_catalog.pg_auth_members](https://www.postgresql.org/docs/14/catalog-pg-auth-members.html)
- [ ] [pg_catalog.pg_collation](https://www.postgresql.org/docs/14/catalog-pg-collation.html)
- [ ] [pg_catalog.pg_conversion](https://www.postgresql.org/docs/14/catalog-pg-conversion.html)
- [ ] [pg_catalog.pg_event_trigger](https://www.postgresql.org/docs/14/catalog-pg-event-trigger.html)
- [ ] [pg_catalog.pg_extension](https://www.postgresql.org/docs/14/catalog-pg-extension.html)
- [ ] [pg_catalog.pg_foreign_data_wrapper](https://www.postgresql.org/docs/14/catalog-pg-foreign-data-wrapper.html)
- [ ] [pg_catalog.pg_foreign_server](https://www.postgresql.org/docs/14/catalog-pg-foreign-server.html)
- [ ] [pg_catalog.pg_foreign_table](https://www.postgresql.org/docs/14/catalog-pg-foreign-table.html)
- [ ] [pg_catalog.pg_language](https://www.postgresql.org/docs/14/catalog-pg-language.html)
- [ ] [pg_catalog.pg_opclass](https://www.postgresql.org/docs/14/catalog-pg-opclass.html)
- [ ] [pg_catalog.pg_opfamily](https://www.postgresql.org/docs/14/catalog-pg-opfamily.html)
- [ ] [pg_catalog.pg_operator](https://www.postgresql.org/docs/14/catalog-pg-operator.html)
- [ ] [pg_catalog.pg_policies](https://www.postgresql.org/docs/14/view-pg-policies.html)
- [ ] [pg_catalog.pg_sequence](https://www.postgresql.org/docs/14/catalog-pg-sequence.html)
- [ ] [pg_catalog.pg_stat_activity](https://www.postgresql.org/docs/14/monitoring-stats.html#MONITORING-PG-STAT-ACTIVITY-VIEW)
- [ ] [pg_catalog.pg_timezone_name](https://www.postgresql.org/docs/14/view-pg-timezone-names.html)
- [ ] [pg_catalog.pg_timezone_abbrevs](https://www.postgresql.org/docs/14/view-pg-timezone-abbrevs.html)
- [ ] [pg_catalog.pg_trigger](https://www.postgresql.org/docs/14/catalog-pg-trigger.html)
- [ ] [pg_catalog.pg_user_mapping](https://www.postgresql.org/docs/14/catalog-pg-user-mapping.html)
- [ ] [pg_depend](https://www.postgresql.org/docs/14/catalog-pg-depend.html)
- [ ] [pg_rewrite](https://www.postgresql.org/docs/14/catalog-pg-rewrite.html)

**Comment by hlcianfagna** [comment]
Regarding the missing pg_catalog tables, trying to create mocks currently results on "Cannot create relation in read-only schema", perhaps allowing that could be a low-cost way of enabling workarounds?

**Comment by hlcianfagna** [comment]
> Regarding the missing pg_catalog tables, trying to create mocks currently results on "Cannot create relation in read-only schema", perhaps allowing that could be a low-cost way of enabling workarounds?

This can be worked around by creating the mocks in another schema and setting search_path to look in that other schema before pg_catalog

**Comment by amotl** [comment]
Hi. We've refreshed the documentation about how to connect to CrateDB using DataGrip and the [CrateDB JDBC Driver](https://cratedb.com/docs/jdbc/). It is currently the best way forward until CrateDB will be compatible enough with PostgreSQL to cope with use by upstream canonical [pgJDBC](https://jdbc.postgresql.org/) within DataGrip.

https://cratedb.com/docs/guide/integrate/datagrip/
