### ISSUE TITLE
overview/meta: Insert performance improvements

### ISSUE THREAD

**Issue by mfussenegger** [crate/crate#12484]
Overview issue to track potential insert performance improvements.

This is WIP.

- [ ] https://github.com/crate/crate/issues/12475
- [ ] https://github.com/crate/crate/issues/11652
- [ ] https://github.com/crate/crate/issues/12482
