### ISSUE TITLE
Function registry overhaul

### ISSUE THREAD

**Issue by seut** [crate/crate#9901]
# Function registry overhaul 

## Intro

Our existing function registry lacks some features like overloading or providing all information for a `information_schema.pg_proc` table.

### Function registration and matching

Each function is registering a custom (or othwise generated) `FunctionResolver` instance using the full-qualified `FunctionName` as the key.

When an existing `FunctionResolver` for a given function name is found, the resolver:
 - validates/matches given argument data types if not successful bail out
 - creates a `FunctionImplementation` instance based on the given argument data types

Data type matching is done by the `FuncParams` and `Param` implementations.

Supported features:
  - define allowed types
  - define variable arity of the one or more argument types, including maximum occurences
  - do type coercion respecting type precedence
  - downcast literals to ensure storage (lucene) indices usages (but doing this inside the analyzer/planner leads to bugs on correct type resolving https://github.com/crate/crate/issues/9652)

Missing features:
  - define type contraints (e.g. `foo(E, array(E))` where the data type of `E` must match)
  - define return data type
  - possibility to prevent type coercion

Thus, providing different implementations for different argument types (parameter overloading) is possible but requires a custom `FunctionResolver` implementation with custom logic for type (constraints) validation and processing.
Exposing alls registered functions including the different supported argument type variants is not possible because a `FunctionResolver` implementation does not provide statical information, user given arguments are needed for that.

## Requirements and proposals

 - [x] Register functions by purely statical information in order to be able to expose the supported function signatures.
       Required to fully implement `information_schema.pg_proc`. (https://github.com/crate/crate/pull/9763, https://github.com/crate/crate/pull/9853).
     
 - [x] Add support for ensuring type variable constraints by definition instead of custom code (`foo(E, array(E))`). (https://github.com/crate/crate/pull/9763)
 
 - [x] Add support for function signature overloads by definition/registry. (https://github.com/crate/crate/pull/9763)

 - [x] Add logic to select the most specific function if multiple function are matching (e.g. due to type coercion). (https://github.com/crate/crate/pull/9847, https://github.com/crate/crate/pull/9872)
 
 - [x] Convert all functions to the new signature based registry

 - [x] Fix arithmetic issues when using non-floating and floating numeric values (#9652, #10070)
 
 - [x] Expose all available functions via `information_schema.pg_proc`. (#9750,  #9916)

 - [x] Move (re-implement) storage engine related logic like downcasts of literals out of the analysis and closer to the storage engine. (#10076)

 - [x] Remove old `FunctionIdent` based registry and add BWC logic (#10101).

 - [x] Deprecate `FunctionIdent` and `FunctionInfo` and generated them using the signature (#10138).
    
 - [ ] Remove `FunctionIdent` and `FunctionInfo` in favour of `Signature`. (5.0 only)
